site_name: isobar-ext
theme:
  name: material
  features:
    - navigation.tabs

repo_name: piotereks/isobar-ext
repo_url: https://github.com/piotereks/isobar-ext



markdown_extensions:
 - markdown.extensions.admonition
 - markdown.extensions.codehilite
 - pymdownx.tabbed

nav:
 - Home:
   - Home: index.md
   - Getting started: getting-started.md
   - Example: example.md
   - Examples: examples.md
   - Source code: source-code.md
   - About the project: about.md
   - Contributing: contributing.md
   - License: license.md
 - Timelines:
   - About timelines: timelines/index.md
 - Patterns:
   - About patterns: patterns/index.md
   - Pattern library reference: patterns/library.md
 - Events:
   - Events: events/index.md
   - Note events: events/note.md
   - Control events: events/control.md
   - Action events: events/action.md
 - Devices and I/O:
   - Devices and I/O: devices/index.md
   - MIDI: devices/midi.md
   - Virtual MIDI devices: devices/virtual-midi-devices.md
   - MIDI files: devices/midifile.md
   - OSC: devices/osc.md
   - Signal Flow: devices/signalflow.md
   - SuperCollider: devices/supercollider.md
